name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: nightly

      - name: Install lld (macos)
        if: matrix.os == 'macos-latest'
        run: brew install lld

      - name: Install lld (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y lld

      - name: Compile STB libraries (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: make -C "$HOME/odin/vendor/stb/src"

      - name: Compile box2d libraries (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: $HOME/odin/vendor/box2d/build_box2d.sh

      - uses: actions/checkout@v4

      - name: test_all_examples
        run: odin run tools/test_examples

      - name: raylib_ports/shaders_texture_waves
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style

      - name: raylib_ports/shaders_texture_waves (debug)
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style -debug

      - name: raylib_ports/shaders_texture_waves (gl)
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style -define:KARL2D_RENDER_BACKEND=gl

      - name: raylib_ports/shaders_texture_waves (gl, debug)
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=gl

      - name: raylib_ports/shaders_texture_waves (gl)
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style -define:KARL2D_RENDER_BACKEND=nil

      - name: raylib_ports/shaders_texture_waves (nil, debug)
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=nil

      - name: raylib_ports/bunnymark
        run: odin check examples/raylib_ports/bunnymark -vet -strict-style

      - name: raylib_ports/bunnymark (debug)
        run: odin check examples/raylib_ports/bunnymark -vet -strict-style -debug

      - name: raylib_ports/bunnymark (gl)
        run: odin check examples/raylib_ports/bunnymark -vet -strict-style -define:KARL2D_RENDER_BACKEND=gl

      - name: raylib_ports/bunnymark (gl, debug)
        run: odin check examples/raylib_ports/bunnymark -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=gl

      - name: raylib_ports/bunnymark (gl)
        run: odin check examples/raylib_ports/bunnymark -vet -strict-style -define:KARL2D_RENDER_BACKEND=nil

      - name: raylib_ports/bunnymark (nil, debug)
        run: odin check examples/raylib_ports/bunnymark -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=nil

      - name: raylib_ports/bunnymark (web)
        run: odin run build_web -vet -strict-style -- examples/raylib_ports/bunnymark

      - name: raylib_ports/bunnymark (web, debug)
        run: odin run build_web -vet -strict-style -- examples/raylib_ports/bunnymark -debug

      - name: verify karl2d.doc.odin
        run: odin run tools/api_verifier
