name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *


jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: nightly
          
      - uses: actions/checkout@v4


      - name: minimal
        run: odin check examples/minimal -vet -strict-style

      - name: minimal (debug)
        run: odin check examples/minimal -vet -strict-style -debug

      - name: minimal (gl)
        run: odin check examples/minimal -vet -strict-style -define:KARL2D_RENDER_BACKEND=gl

      - name: minimal (gl, debug)
        run: odin check examples/minimal -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=gl

      - name: minimal (gl)
        run: odin check examples/minimal -vet -strict-style -define:KARL2D_RENDER_BACKEND=nil

      - name: minimal (nil, debug)
        run: odin check examples/minimal -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=nil

      - name: minimal (web)
        run: odin run build_web -vet -strict-style -- examples/minimal_web

      - name: minimal (web, debug)
        run: odin run build_web -vet -strict-style -- examples/minimal_web -debug


      - name: snake
        run: odin check examples/snake -vet -strict-style

      - name: snake (debug)
        run: odin check examples/snake -vet -strict-style -debug

      - name: snake (gl)
        run: odin check examples/snake -vet -strict-style -define:KARL2D_RENDER_BACKEND=gl

      - name: snake (gl, debug)
        run: odin check examples/snake -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=gl

      - name: snake (gl)
        run: odin check examples/snake -vet -strict-style -define:KARL2D_RENDER_BACKEND=nil

      - name: snake (nil, debug)
        run: odin check examples/snake -vet -strict-style -debug -define:KARL2D_RENDER_BACKEND=nil

      - name: snake (web)
        run: odin run build_web -vet -strict-style -- examples/snake

      - name: snake (web, debug)
        run: odin run build_web -vet -strict-style -- examples/snake -debug


      - name: 2d_camera
        run: odin check examples/raylib_ports/2d_camera -vet -strict-style

      - name: 2d_camera (debug)
        run: odin check examples/raylib_ports/2d_camera -vet -strict-style -debug

      - name: shaders_texture_waves
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style

      - name: shaders_texture_waves (debug)
        run: odin check examples/raylib_ports/shaders_texture_waves -vet -strict-style -debug

      - name: gamepad
        run: odin check examples/gamepad -vet -strict-style

      - name: gamepad (debug)
        run: odin check examples/gamepad -vet -strict-style -debug
